-- ============================================================================
-- SNOWFLAKE MEDALLION ARCHITECTURE PROJECT 
-- By: Gayathry Vinod
-- =========================================================================================
-- BRONZE LAYER 
-- ==========================================================================================

-- CUSTOMER TABLE 
CREATE OR REPLACE TABLE BRONZE.BRONZE_CUSTOMERS AS
SELECT
    TRIM(CUSTOMER_ID) AS CUSTOMER_ID,
    TRIM(CUSTOMER_UNIQUE_ID) AS CUSTOMER_UNIQUE_ID,
    CUSTOMER_ZIP_CODE_PREFIX,
    UPPER(TRIM(CUSTOMER_CITY)) AS CUSTOMER_CITY,
    UPPER(TRIM(CUSTOMER_STATE)) AS CUSTOMER_STATE
FROM RAW.CUSTOMERS;

SELECT * FROM BRONZE.BRONZE_CUSTOMERS;

-- ORDERS TABLE 
CREATE OR REPLACE TABLE BRONZE.BRONZE_ORDERS AS
SELECT
    ORDER_ID,
    CUSTOMER_ID,
    ORDER_STATUS,
    TO_TIMESTAMP_NTZ(ORDER_PURCHASE_TIMESTAMP) AS ORDER_PURCHASE_TS,
    TO_TIMESTAMP_NTZ(ORDER_APPROVED_AT) AS ORDER_APPROVED_TS,
    TO_TIMESTAMP_NTZ(ORDER_DELIVERED_CUSTOMER_DATE) AS ORDER_DELIVERED_TS
FROM RAW.ORDERS;

-- ORDER_ITEMS
CREATE OR REPLACE TABLE BRONZE.BRONZE_ORDER_ITEMS AS
SELECT
    TRIM(ORDER_ID) AS ORDER_ID,
    ORDER_ITEM_ID,
    TRIM(PRODUCT_ID) AS PRODUCT_ID,
    TRIM(SELLER_ID) AS SELLER_ID,
    SHIPPING_LIMIT_DATE AS SHIPPING_LIMIT_TS,
    PRICE,
    FREIGHT_VALUE
FROM RAW.ORDER_ITEMS;

SELECT * FROM BRONZE_ORDER_ITEMS;

-- PRODUCTS
CREATE OR REPLACE TABLE BRONZE.BRONZE_PRODUCTS AS
SELECT TRIM(PRODUCT_ID) AS PRODUCT_ID,
    LOWER(TRIM(PRODUCT_CATEGORY_NAME)) AS PRODUCT_CATEGORY_NAME,
    PRODUCT_NAME_LENGTH,
    PRODUCT_DESCRIPTION_LENGTH,
    PRODUCT_PHOTOS_QTY,
    PRODUCT_WEIGHT_G,
    PRODUCT_LENGTH_CM,
    PRODUCT_HEIGHT_CM,
    PRODUCT_WIDTH_CM
FROM RAW.PRODUCTS;

-- PAYMENTS
CREATE OR REPLACE TABLE BRONZE.BRONZE_PAYMENTS AS
SELECT
    TRIM(ORDER_ID) AS ORDER_ID,
    PAYMENT_SEQUENTIAL,
    UPPER(TRIM(PAYMENT_TYPE)) AS PAYMENT_TYPE,
    PAYMENT_INSTALLMENTS,
    ROUND(PAYMENT_VALUE, 2)AS PAYMENT_VALUE
FROM RAW.PAYMENTS;

-- REVIEWS
CREATE OR REPLACE TABLE BRONZE.BRONZE_REVIEWS AS
SELECT
    TRIM(REVIEW_ID) AS REVIEW_ID,
    TRIM(ORDER_ID) AS ORDER_ID,
    REVIEW_SCORE,
    TRIM(REVIEW_COMMENT_TITLE) AS REVIEW_COMMENT_TITLE,
    TRIM(REVIEW_COMMENT_MESSAGE) AS REVIEW_COMMENT_MESSAGE,
    REVIEW_CREATION_DATE AS REVIEW_CREATION_TS,
    REVIEW_ANSWER_TIMESTAMP AS REVIEW_ANSWER_TS
FROM RAW.REVIEWS;

-- SELLERS
CREATE OR REPLACE TABLE BRONZE.BRONZE_SELLERS AS
SELECT DISTINCT
    TRIM(SELLER_ID) AS SELLER_ID,
    SELLER_ZIP_CODE_PREFIX,
    UPPER(TRIM(SELLER_CITY)) AS SELLER_CITY,
    UPPER(TRIM(SELLER_STATE)) AS SELLER_STATE
FROM RAW.SELLERS;

-- GEOLOCATION 
CREATE OR REPLACE TABLE BRONZE.BRONZE_GEOLOCATION AS
SELECT
    GEOLOCATION_ZIP_CODE_PREFIX,
    GEOLOCATION_LAT,
    GEOLOCATION_LNG,
    UPPER(TRIM(GEOLOCATION_CITY)) AS GEOLOCATION_CITY,
    UPPER(TRIM(GEOLOCATION_STATE)) AS GEOLOCATION_STATE
FROM RAW.GEOLOCATION;

-- PRODUCT_CATEGORY_TRANSLATION 
CREATE OR REPLACE TABLE BRONZE.BRONZE_PRODUCT_CATEGORY_TRANSLATION AS
SELECT
    LOWER(TRIM(PRODUCT_CATEGORY_NAME)) AS PRODUCT_CATEGORY_NAME,
    TRIM(PRODUCT_CATEGORY_NAME_ENGLISH) AS PRODUCT_CATEGORY_NAME_ENGLISH
FROM RAW.PRODUCT_CATEGORY_NAME_TRANSLATION;

-- VALIDATING BRONZE LAYER 
SELECT * FROM BRONZE_PRODUCTS;
SELECT * FROM BRONZE_SELLERS;
