-- =========================================================================================
-- SNOWFLAKE MEDALLION ARCHITECTURE PROJECT 
-- By: Gayathry Vinod
-- =========================================================================================
-- GOLD LAYER 
-- ==========================================================================================

-- CREATE BUSINESS READY DATA MARTS

-- SALES DAILY
CREATE OR REPLACE TABLE GOLD.SALES_DAILY AS
SELECT
    CAST(ORDER_PURCHASE_TS AS DATE) AS ORDER_DATE,
    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
    SUM(PRICE) AS SALES_AMOUNT,
    SUM(FREIGHT_VALUE) AS FREIGHT_AMOUNT
FROM SILVER.FACT_ORDER_ITEMS
GROUP BY 1;

-- SALES BY STATE
CREATE OR REPLACE TABLE GOLD.SALES_BY_STATE AS
SELECT
    DC.CUSTOMER_STATE,
    COUNT(DISTINCT F.ORDER_ID) AS TOTAL_ORDERS,
    SUM(F.PRICE) AS TOTAL_SALES
FROM SILVER.FACT_ORDER_ITEMS F
JOIN SILVER.DIM_CUSTOMER DC
    ON F.CUSTOMER_KEY = DC.CUSTOMER_KEY
GROUP BY 1;

-- PRODUCT PERFORMANCE 
CREATE OR REPLACE TABLE GOLD.PRODUCT_PERFORMANCE AS
SELECT
    DP.PRODUCT_CATEGORY_NAME_ENGLISH,
    COUNT(*) AS ITEMS_SOLD,
    SUM(F.PRICE) AS REVENUE,
    AVG(F.REVIEW_SCORE) AS AVG_REVIEW_SCORE
FROM SILVER.FACT_ORDER_ITEMS F
JOIN SILVER.DIM_PRODUCT DP
    ON F.PRODUCT_KEY = DP.PRODUCT_KEY
GROUP BY 1;

-- CUSTOMER ANALYTICS 
CREATE OR REPLACE TABLE GOLD.CUSTOMER_ANALYTICS AS
SELECT
    DC.CUSTOMER_STATE,
    COUNT(DISTINCT F.CUSTOMER_KEY) AS CUSTOMERS,
    COUNT(DISTINCT F.ORDER_ID) AS ORDERS,
    SUM(F.PRICE) AS REVENUE
FROM SILVER.FACT_ORDER_ITEMS F
JOIN SILVER.DIM_CUSTOMER DC
    ON F.CUSTOMER_KEY = DC.CUSTOMER_KEY
GROUP BY 1;

-- ---------------------------------------------------------------------------------
-- VALIDATION 
-- ---------------------------------------------------------------------------------

SELECT *
FROM GOLD.SALES_DAILY
ORDER BY ORDER_DATE DESC
LIMIT 20;

SELECT *
FROM GOLD.SALES_BY_STATE
ORDER BY TOTAL_SALES DESC;
