-- ============================================================================
-- SNOWFLAKE MEDALLION ARCHITECTURE PROJECT 
-- By: Gayathry Vinod
-- ============================================================================

-- =============================================================================================
-- RAW LAYER 
-- =============================================================================================

CREATE DATABASE ECOMMERCE_DE;
USE DATABASE ECOMMERCE_DE;

CREATE SCHEMA RAW;
CREATE SCHEMA BRONZE;
CREATE SCHEMA SILVER;
CREATE SCHEMA GOLD;

CREATE WAREHOUSE DE_WH
WITH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

USE DATABASE ECOMMERCE_DE;
USE SCHEMA RAW;
CREATE STAGE RAW_CSV_STAGE;

-- =====================================================================================================
-- RAW DATA INGESTION 
-- ------------------------------------------------------------------------------------------------------
-- CUSTOMERS TABLE
CREATE OR REPLACE TABLE CUSTOMERS (
    CUSTOMER_ID VARCHAR(50),
    CUSTOMER_UNIQUE_ID VARCHAR(50),
    CUSTOMER_ZIP_CODE_PREFIX INTEGER,
    CUSTOMER_CITY VARCHAR(100),
    CUSTOMER_STATE VARCHAR(10)
);
DESC TABLE CUSTOMERS;
SELECT * FROM RAW.CUSTOMERS;
--TRUNCATE TABLE ECOMMERCE_DE.RAW.CUSTOMERS;
SELECT COUNT(*) FROM RAW.CUSTOMERS;

-- ORDERS TABLE 
CREATE OR REPLACE TABLE ORDERS (
    ORDER_ID VARCHAR,
    CUSTOMER_ID VARCHAR,
    ORDER_STATUS VARCHAR,
    ORDER_PURCHASE_TIMESTAMP TIMESTAMP_NTZ,
    ORDER_APPROVED_AT TIMESTAMP_NTZ,
    ORDER_DELIVERED_CARRIER_DATE TIMESTAMP_NTZ,
    ORDER_DELIVERED_CUSTOMER_DATE TIMESTAMP_NTZ,
    ORDER_ESTIMATED_DELIVERY_DATE TIMESTAMP_NTZ
);
SELECT * FROM RAW.ORDERS;

-- ORDER ITEMS TABLE
CREATE OR REPLACE TABLE RAW.ORDER_ITEMS (
    ORDER_ID VARCHAR,
    ORDER_ITEM_ID NUMBER,
    PRODUCT_ID VARCHAR,
    SELLER_ID VARCHAR,
    SHIPPING_LIMIT_DATE TIMESTAMP_NTZ,
    PRICE NUMBER(10,2),
    FREIGHT_VALUE NUMBER(10,2)
);
SELECT * FROM RAW.ORDER_ITEMS;

-- PAYMENTS TABLE 
CREATE OR REPLACE TABLE RAW.PAYMENTS (
    ORDER_ID VARCHAR,
    PAYMENT_SEQUENTIAL NUMBER,
    PAYMENT_TYPE VARCHAR,
    PAYMENT_INSTALLMENTS NUMBER,
    PAYMENT_VALUE NUMBER(10,2)
);
SELECT * FROM RAW.PAYMENTS;

-- PRODUCTS TABLE
CREATE OR REPLACE TABLE RAW.PRODUCTS (
    PRODUCT_ID VARCHAR,
    PRODUCT_CATEGORY_NAME VARCHAR,
    PRODUCT_NAME_LENGTH NUMBER,
    PRODUCT_DESCRIPTION_LENGTH NUMBER,
    PRODUCT_PHOTOS_QTY NUMBER,
    PRODUCT_WEIGHT_G NUMBER,
    PRODUCT_LENGTH_CM NUMBER,
    PRODUCT_HEIGHT_CM NUMBER,
    PRODUCT_WIDTH_CM NUMBER
);
SELECT * FROM RAW.PRODUCTS;

-- REVIEWS TABLE 
CREATE OR REPLACE TABLE RAW.REVIEWS (
    REVIEW_ID VARCHAR,
    ORDER_ID VARCHAR,
    REVIEW_SCORE NUMBER,
    REVIEW_COMMENT_TITLE VARCHAR,
    REVIEW_COMMENT_MESSAGE VARCHAR,
    REVIEW_CREATION_DATE TIMESTAMP_NTZ,
    REVIEW_ANSWER_TIMESTAMP TIMESTAMP_NTZ
);
SELECT * FROM RAW.REVIEWS;

-- SELLERS TABLE 
CREATE OR REPLACE TABLE RAW.SELLERS (
    SELLER_ID VARCHAR,
    SELLER_ZIP_CODE_PREFIX NUMBER,
    SELLER_CITY VARCHAR,
    SELLER_STATE VARCHAR
);
SELECT * FROM RAW.SELLERS;

-- GEOLOCATION TABLE 
CREATE OR REPLACE TABLE RAW.GEOLOCATION (
    GEOLOCATION_ZIP_CODE_PREFIX NUMBER,
    GEOLOCATION_LAT FLOAT,
    GEOLOCATION_LNG FLOAT,
    GEOLOCATION_CITY VARCHAR,
    GEOLOCATION_STATE VARCHAR
);
SELECT * FROM RAW.GEOLOCATION;

-- PRODUCT CATEGORY NAME TRANSLATION TABLE
CREATE OR REPLACE TABLE RAW.PRODUCT_CATEGORY_NAME_TRANSLATION (
    PRODUCT_CATEGORY_NAME VARCHAR,
    PRODUCT_CATEGORY_NAME_ENGLISH VARCHAR
);
SELECT * FROM RAW.PRODUCT_CATEGORY_NAME_TRANSLATION;
