-- ============================================================================
-- SNOWFLAKE MEDALLION ARCHITECTURE PROJECT 
-- By: Gayathry Vinod
-- =========================================================================================
-- SILVER LAYER 
-- ==========================================================================================

-- CREATE FACT AND DIMENSION TABLES 

-- CUSTOMER (DIMENSION)
CREATE OR REPLACE TABLE SILVER.DIM_CUSTOMER AS
SELECT
    ROW_NUMBER() OVER (ORDER BY CUSTOMER_ID) AS CUSTOMER_KEY,
    CUSTOMER_ID,
    CUSTOMER_UNIQUE_ID,
    CUSTOMER_CITY,
    CUSTOMER_STATE
FROM BRONZE.BRONZE_CUSTOMERS;

SELECT * FROM SILVER.DIM_CUSTOMER;
SELECT COUNT(DISTINCT CUSTOMER_ID) FROM SILVER.DIM_CUSTOMER;

-- PRODUCT DIMENSION TABLE
CREATE OR REPLACE TABLE SILVER.DIM_PRODUCT AS
SELECT
    ROW_NUMBER() OVER (ORDER BY P.PRODUCT_ID) AS PRODUCT_KEY,
    P.PRODUCT_ID,
    P.PRODUCT_CATEGORY_NAME,
    T.PRODUCT_CATEGORY_NAME_ENGLISH,
    P.PRODUCT_NAME_LENGTH,
    P.PRODUCT_DESCRIPTION_LENGTH,
    P.PRODUCT_PHOTOS_QTY,
    P.PRODUCT_WEIGHT_G,
    P.PRODUCT_LENGTH_CM,
    P.PRODUCT_HEIGHT_CM,
    P.PRODUCT_WIDTH_CM
FROM BRONZE.BRONZE_PRODUCTS P
LEFT JOIN BRONZE.BRONZE_PRODUCT_CATEGORY_TRANSLATION T
ON P.PRODUCT_CATEGORY_NAME = T.PRODUCT_CATEGORY_NAME;

-- SELLER DIMENSION TABLE 
CREATE OR REPLACE TABLE SILVER.DIM_SELLER AS
SELECT
    ROW_NUMBER() OVER (ORDER BY SELLER_ID) AS SELLER_KEY,
    SELLER_ID,
    SELLER_CITY,
    SELLER_STATE
FROM BRONZE.BRONZE_SELLERS;

-- ----------- FACT TABLES -------------
-- ORDER FACT TABLE 
/* 
CREATE OR REPLACE TABLE SILVER.FACT_ORDERS AS
SELECT
    O.ORDER_ID,
    DC.CUSTOMER_KEY,
    DP.PRODUCT_KEY,
    DS.SELLER_KEY,
    O.ORDER_PURCHASE_TS,
    O.ORDER_APPROVED_TS,
    O.ORDER_DELIVERED_TS,
    O.ORDER_STATUS,
    OI.ORDER_ITEM_ID,
    OI.PRICE,
    OI.FREIGHT_VALUE,
    P.PAYMENT_VALUE,
    P.PAYMENT_INSTALLMENTS,
    P.PAYMENT_TYPE,
    R.REVIEW_SCORE
FROM BRONZE.BRONZE_ORDERS O

INNER JOIN SILVER.DIM_CUSTOMER DC
ON O.CUSTOMER_ID = DC.CUSTOMER_ID

LEFT JOIN BRONZE.BRONZE_ORDER_ITEMS OI
ON O.ORDER_ID = OI.ORDER_ID

LEFT JOIN SILVER.DIM_PRODUCT DP
ON OI.PRODUCT_ID = DP.PRODUCT_ID

LEFT JOIN SILVER.DIM_SELLER DS
ON OI.SELLER_ID = DS.SELLER_ID

LEFT JOIN BRONZE.BRONZE_PAYMENTS P
ON O.ORDER_ID = P.ORDER_ID

LEFT JOIN BRONZE.BRONZE_REVIEWS R
ON O.ORDER_ID = R.ORDER_ID; */

-- PAYMENT AGGREGATE (To prevent duplicate rows in order facts)
CREATE OR REPLACE TABLE SILVER.FACT_ORDER_ITEMS AS
WITH PAYMENT_AGG AS (
    SELECT
        ORDER_ID,
        SUM(PAYMENT_VALUE) AS TOTAL_PAYMENT_VALUE,
        MAX(PAYMENT_INSTALLMENTS) AS PAYMENT_INSTALLMENTS
    FROM BRONZE.BRONZE_PAYMENTS
    GROUP BY ORDER_ID
),

REVIEW_AGG AS (
    SELECT
        ORDER_ID,
        AVG(REVIEW_SCORE) AS REVIEW_SCORE
    FROM BRONZE.BRONZE_REVIEWS
    GROUP BY ORDER_ID
)

SELECT
    O.ORDER_ID,
    DC.CUSTOMER_KEY,
    DP.PRODUCT_KEY,
    DS.SELLER_KEY,

    O.ORDER_PURCHASE_TS,
    O.ORDER_APPROVED_TS,
    O.ORDER_DELIVERED_TS,
    O.ORDER_STATUS,

    OI.ORDER_ITEM_ID,
    OI.PRICE,
    OI.FREIGHT_VALUE,

    P.TOTAL_PAYMENT_VALUE,
    P.PAYMENT_INSTALLMENTS,

    R.REVIEW_SCORE

FROM BRONZE.BRONZE_ORDER_ITEMS OI

INNER JOIN BRONZE.BRONZE_ORDERS O
    ON OI.ORDER_ID = O.ORDER_ID

INNER JOIN SILVER.DIM_CUSTOMER DC
    ON O.CUSTOMER_ID = DC.CUSTOMER_ID

LEFT JOIN SILVER.DIM_PRODUCT DP
    ON OI.PRODUCT_ID = DP.PRODUCT_ID

LEFT JOIN SILVER.DIM_SELLER DS
    ON OI.SELLER_ID = DS.SELLER_ID

LEFT JOIN PAYMENT_AGG P
    ON O.ORDER_ID = P.ORDER_ID

LEFT JOIN REVIEW_AGG R
    ON O.ORDER_ID = R.ORDER_ID;


-- ------------------------------------------------------------------------
-- VALIDATING SILVER LAYER 
-- --------------------------------------------------------------------------

-- ROW COUNT CHECKS
SELECT COUNT(*) FROM SILVER.DIM_CUSTOMER;
SELECT COUNT(*) FROM SILVER.DIM_PRODUCT;
SELECT COUNT(*) FROM SILVER.DIM_SELLER;
SELECT COUNT(*) FROM SILVER.FACT_ORDER_ITEMS;

-- NULL FOREIGN KEYS 
SELECT COUNT(*)
FROM SILVER.FACT_ORDER_ITEMS
WHERE CUSTOMER_KEY IS NULL;

SELECT COUNT(*)
FROM SILVER.FACT_ORDER_ITEMS
WHERE PRODUCT_KEY IS NULL;

SELECT COUNT(*)
FROM SILVER.FACT_ORDER_ITEMS
WHERE SELLER_KEY IS NULL;

-- DUPLICATE CHECKS 
SELECT CUSTOMER_ID, COUNT(*)
FROM SILVER.DIM_CUSTOMER
GROUP BY 1
HAVING COUNT(*) > 1;

SELECT PRODUCT_ID, COUNT(*)
FROM SILVER.DIM_PRODUCT
GROUP BY 1
HAVING COUNT(*) > 1;

SELECT SELLER_ID, COUNT(*)
FROM SILVER.DIM_SELLER
GROUP BY 1
HAVING COUNT(*) > 1;
